trigger:
 branches:
   include:
    - master
    - develop
 paths:
   include: 
    - src/landing/*

pr: none

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
    ng build -c=build-prod
  workingDirectory: src/landing
  displayName: 'npm install and build'

- powershell: |
   $indexHtml = "index.html"
   $buildId = $(Build.BuildId)
   (Get-Content $indexHtml).replace("-build.counter-", $buildId) | Set-Content $indexHtml
  workingDirectory: 'src/landing/dist/onshop-landing'
  displayName: 'PowerShell Script'

- task: CopyFiles@2
  displayName: 'Copy web-config'
  inputs:
    sourceFolder: src/landing
    contents: |
      web.config
    targetFolder: src/landing/dist/onshop-landing

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: 'src/landing/dist/onshop-landing'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'





